const GRID_GAP = 50
const MAX_SCALE = 3
const MIN_SCALE = 0.3
const SCALE_STEP = 0.2
const BORDER_COLOR1 = 'rgba(0,0,0,0.2)'
const BORDER_COLOR2 = 'rgba(0,0,0,0.1)'
export {GRID_GAP,MAX_SCALE,MIN_SCALE,BORDER_COLOR1,BORDER_COLOR2,SCALE_STEP}
