const POINT_COLOR = 'rgb(34, 123, 218)'
const HOVER_POINT_COLOR = 'rgb(69, 146, 228)'

const POINT_RADIUS = 5
const HOVER_POINT_RADIUS = 8
export {POINT_COLOR,POINT_RADIUS,HOVER_POINT_RADIUS,HOVER_POINT_COLOR}
